### ISSUE TITLE
[Maintenance]: VFX Reference Platform CY24

### ISSUE THREAD

**Issue by compaga** [AcademySoftwareFoundation/OpenRV#366]
- Python 3.11.x
- Qt 6.5.x
- Open EXR 3.2.x
- OCIO 2.3.x

[https://vfxplatform.com](https://vfxplatform.com) 
```[tasklist]
### Tasks
- [ ] https://github.com/AcademySoftwareFoundation/OpenRV/issues/367
- [ ] https://github.com/AcademySoftwareFoundation/OpenRV/issues/368
- [ ] https://github.com/AcademySoftwareFoundation/OpenRV/issues/369
- [ ] https://github.com/AcademySoftwareFoundation/OpenRV/issues/370
```

**Comment by pbergeron-adsk** [comment]
@compaga @cedrik-fuoco-adsk After verification, the following:

- Python 3.11.x
- Qt 6.5.x
- Open EXR 3.2.x
- OCIO 2.3.x

Are indeed now supported in OpenRV main. Should probably close this issue unless you have something else to add.

**Comment by cedrik-fuoco-adsk** [comment]
VFX2024 has been completed since the feature/qt6 merge into main. Closing the issue.
